IBM/cp4i-deployment-samples

products/bash/release-products.sh
Assetrepo install
https://github.ibm.com/cp4i/icp4i-sagan/issues/661
=> Assetrepo install

products/bash/release-products.sh
Change replica count for ace dashboard
https://github.ibm.com/cp4i/icp4i-sagan/issues/682
=> Change replica count for ace dashboard

products/bash/ar_remote_create.sh
https://github.ibm.com/cp4i/cloudpak-for-integration-case/pull/155
https://github.ibm.com/cp4i/icp4i-sagan/issues/662
https://cloud.ibm.com/schematics/workspaces/ibm-cp-integration-05-14-2020-kirkle-08cb232b-a6f0-48/log/f963511f9d57e322e7120b2ae07fb9ee?region=
https://asset-repo-demo-assetrepo.kirk-sad-ec111ed5d7db435e1c5eeeb4400d693f-0000.us-south.containers.appdomain.cloud/e8a96c69-7c86-4483-85ff-b83e6f6c3c37/browse
=> Ar remote setup

products/bash/release-products.sh
Enable tracing installation
https://github.ibm.com/cp4i/icp4i-sagan/issues/721
=> Enable tracing installation

products/bash/release-products.sh
Requires editing the tracing charts before installing
Tested on my dans-demo cluster resulting in:
=> Set tracing sample size to 100%

products/bash/release-products.sh
https://cloud.ibm.com/schematics/workspaces/ibm-cp-integration-06-04-2020-kirk-4535c655-0aa5-46/log/c1d81dabb51712e08a16f2eadf8eb061?region=
https://github.ibm.com/cp4i/icp4i-sagan/issues/735
=> Adding in dev to release names for future instance seperation

products/bash/release-products.sh
=> updating to version 9.6

DrivewayDentDeletion/cicd-webhook-triggers.yaml, DrivewayDentDeletion/prereqs.sh
Helm ace deploy and setup pre-reqs
https://github.ibm.com/cp4i/icp4i-sagan/issues/765
=> Helm ace deploy and setup pre-reqs

DrivewayDentDeletion/cicd-webhook-triggers.yaml
Helm upgrade restart pod on deployment - use a unique image tags
=> Helm upgrade restart pod on deployment - use a unique image tags

products/bash/release-ace.sh, products/bash/validate-operator-releases.sh
Script running:
Dashboard up:
Designer up:
This also contains the fix that allows a success when the type "deployed" == "true".
=> Ace via ops

products/bash/release-es.sh, products/bash/validate-operator-releases.sh
Release waiting to be ready (NOTE the debug with the actual response is no longer in the code, just there to show what remains in .status.conditions after deleting anything with Type:Warning):
Release being ready:
ES reporting ok:
=> Event streams operators

products/bash/ar_remote_create.sh, products/bash/register-tracing.sh
This pr makes sure we pick up only the route for asset repo when releasing asset repo
https://github.ibm.com/cp4i/icp4i-fermi/issues/70
=> Asset repo fix

products/bash/configure-apic-v10.sh
Ignore the branch name. Made a mistake creating that :p
=> fixing apic config cp4i/icp4i-fermi#72

products/bash/ar_remote_create.sh
=> removing https:// from the uri

DrivewayDentDeletion/Operators/cicd-webhook-triggers.yaml
Run all build tasks in series - ace after mq
=> Run all build tasks in series - ace after mq

products/bash/ar_remote_create.sh, products/bash/configure-apic-v10.sh, products/bash/release-apic.sh, products/bash/release-ar.sh, products/bash/release-es.sh, products/bash/release-mq.sh, products/bash/release-tracing.sh
Able to create assets from AR:
=> Different release names

DrivewayDentDeletion/Operators/cicd-webhook-triggers.yaml
Especially important for ephemeral storage
=> Build in parallel with limits/requests

EventEnabledInsurance/prereqs.sh
Dummy Prereqs for Event enabled insurance demo
=> Dummy Prereqs for Event enabled insurance demo

.gitignore, EventEnabledInsurance/QuoteLifecycleSimulator/Simulator.Dockerfile, EventEnabledInsurance/QuoteLifecycleSimulator/deploy-simulator.sh, EventEnabledInsurance/QuoteLifecycleSimulator/go.mod, EventEnabledInsurance/QuoteLifecycleSimulator/go.sum, EventEnabledInsurance/QuoteLifecycleSimulator/readme.md, EventEnabledInsurance/prereqs.sh
=> Containerize Quote Lifecycle Simulator

EventEnabledInsurance/prereqs.sh
Update eei prereqs with branch and repo params
=> Update eei prereqs with branch and repo params

products/bash/release-es.sh
Increase the replica count of the zookeeper for event streams to 3
=> increased replicas of zookeeper

EventEnabledInsurance/MQ/Dockerfile, EventEnabledInsurance/build/build.sh, EventEnabledInsurance/build/pipeline.yaml, products/bash/configure-ocp-pipeline.sh
Tested on the dan-eei-mq, results in a new MQ instance with a Quote queue:
=> Build/deploy MQ for EEI

products/bash/ar_remote_create.sh
Retry getting the token and re-get the username/password each time in case it changes
=> Make script be more resilient getting the CS token

products/bash/1-click-install.sh
Fix for -q to take arguments (`demoAPICMailServerPassword`)
=> Fix for -q to take arguments

CommonPipelineResources/cicd-tasks-new.yaml, DrivewayDentDeletion/Operators/apic-resources/apic-api-ddd.yaml, DrivewayDentDeletion/Operators/cicd-dev/cicd-roles.yaml, DrivewayDentDeletion/Operators/cicd-test-apic/cicd-roles.yaml, DrivewayDentDeletion/Operators/cicd-test-apic/cicd-tasks.yaml, DrivewayDentDeletion/Operators/cicd-test/cicd-roles.yaml, DrivewayDentDeletion/Operators/test-api-e2e.sh, EventEnabledInsurance/apic/apic-api-eei.yaml, EventEnabledInsurance/apic/apic-product-eei.yaml, EventEnabledInsurance/build/pipeline.yaml, products/bash/pub-sub-apic.sh, products/bash/register-tracing.sh, products/bash/release-ace-integration-server.sh, products/bash/release-mq.sh
Changes have been made in files used by DDD, so DDD retested:
The EEI POST endpoint was tested using:
```
dan-eei-POST-e2e-lon04 $ API_BASE_URL=$(oc get secret eei-api-endpoint-client-id -o jsonpath='{.data.api}' | base64 --decode)
dan-eei-POST-e2e-lon04 $ API_CLIENT_ID=$(oc get secret eei-api-endpoint-client-id -o jsonpath='{.data.cid}' | base64 --decode)
dan-eei-POST-e2e-lon04 $ 
dan-eei-POST-e2e-lon04 $ curl "${API_BASE_URL}/quote" -H "X-IBM-Client-Id: ${API_CLIENT_ID}" -k \
>   -d $'{\n  "name": "Ronald McGee",\n  "email": "zarhuci@surguf.zm",\n  "age": 68221627,\n  "address": "408 Uneit Manor",\n  "usState": "CT",\n  "licensePlate": "hezihe",\n  "descriptionOfDamage": "56"\n}'
{"name":"Ronald McGee","email":"zarhuci@surguf.zm","age":68221627,"address":"408 Uneit …
```
=> Add APIC to EEI

DrivewayDentDeletion/Operators/readme.md, EventEnabledInsurance/build/pipeline.yaml, EventEnabledInsurance/post-load-test-readme.md, EventEnabledInsurance/post-load-test.sh, EventEnabledInsurance/readme.md
- Create a test script to load test the POST call via APIC
Doc how to
- Run the load script
- Watch the MQ queue grow
- Stop the load script
- Watch the MQ queue shrink
=> Create a test script to load test the POST call and add instructions to README

products/bash/release-tracing.sh
Bumping cr version due to license update
=> Upgrade tracing cr version

products/bash/demos.json, products/bash/example-demos/ccr.yaml, products/bash/example-demos/ma.yaml, products/bash/example-demos/wcb.yaml, products/bash/setup-demos.sh
- Process the list of demos and install. Need to support installing:
- mapping assist
- weather chatbot
=> Install/update demos - mapping assist and weather chatbot

products/bash/setup-demos-readme.md
Fix setup script name in readme
=> Fix setup script name in readme

EventEnabledInsurance/setup-elastic-search.sh, products/bash/release-ace-designer.sh
This PR updates the elastic search operator to the latest version and includes the work around to stop the ace designer ui pod from crashing, leaving designer in a pending state
=> Ace designer and elastic search fix

EventEnabledInsurance/setup-elastic-search.sh, products/bash/ar_remote_create.sh, products/bash/release-psql.sh
owner refs working for elastic search and postgres
added the temp file to ar remote create so that asset repo will work in the demo operator
=> add owner refs to addon and fix ar remote for the operator

DrivewayDentDeletion/Operators/cicd-apply-test-apic-pipeline.sh, DrivewayDentDeletion/Operators/cicd-test-apic/cicd-tasks.yaml, products/bash/example-demos/all.yaml, products/bash/example-demos/ccr.yaml, products/bash/example-demos/ddd.yaml, products/bash/example-demos/eei.yaml, products/bash/example-demos/full.yaml, products/bash/example-demos/ma.yaml, products/bash/example-demos/wcb.yaml, products/bash/license-helper.sh, products/bash/release-ace-dashboard.sh, products/bash/release-ace-designer.sh, products/bash/release-ace-integration-server.sh, products/bash/release-mq.sh, products/bash/setup-demos-readme.md, products/bash/setup-demos.sh
Changes:
- New license variables in demo setup script
- License helper functions
- ACE & MQ release scripts updated to grab licenses from CR
=> Require license input for integration server and queue manager

products/bash/license-helper.sh, products/bash/release-apic.sh, products/bash/release-ar.sh, products/bash/release-mq.sh, products/bash/release-tracing.sh, products/bash/setup-demos.sh
Added licenses to Asset Repo, Tracing and APIC
=> License products

DrivewayDentDeletion/Operators/prereqs.sh, EventEnabledInsurance/prereqs.sh, EventEnabledInsurance/setup-elastic-search.sh, products/bash/configure-apic-v10.sh, products/bash/configure-postgres-db.sh, products/bash/create-ace-config.sh
checks for an existing secret for postgres, life cycle simulator app if it exists use the existing secret
=> No overwrite config

EventEnabledInsurance/readme.md
https://ibm-cloud.slack.com/archives/C016VR7HK42/p1617816290303200?thread_ts=1617812952.302300&cid=C016VR7HK42
=> Resource version eei docs

products/bash/1-click-pre-validation.sh
Matching change made to "main" branch.
=> Enhance/clarify MZR cluster error message

TestgenBookshopAPI/service/bookshop-v1.0.yaml, TestgenBookshopAPI/service/src/books-microservice/handleRequests/Books/handlePost.js, TestgenBookshopAPI/service/src/books-microservice/routes/index.js, TestgenBookshopAPI/service/src/customer-microservice/routes/index.js
The bookshop swagger document and the API implementation do not match
=> The bookshop swagger document and the API implementation do not match

TestgenBookshopAPI/client/Dockerfile, TestgenBookshopAPI/client/README.md, TestgenBookshopAPI/client/requirements.txt, TestgenBookshopAPI/client/scripts/build.sh, TestgenBookshopAPI/service/README.md
- Image for bookshop client
- Readme
- Build script
- Test images
=> Image for bookshop client, readme, build script

products/bash/license-helper.sh
Fix check to get licenses from config map
=> Fix check to get licenses from config map

DrivewayDentDeletion/Operators/cicd-apply-dev-pipeline.sh, DrivewayDentDeletion/Operators/cicd-apply-test-apic-pipeline.sh, DrivewayDentDeletion/Operators/cicd-apply-test-pipeline.sh, DrivewayDentDeletion/Operators/readme.md
Doc how to change the storage classes used for DDD and validate that the storage classes exist.
=> Improve DDD docs and script storage class validation

products/bash/ar_remote_create.sh
As part of this I also removed support for helm installs, now only supports operator
To test I did the following:
1) Delete the demos remotes from the AR UI so it looks like
2) Run the script using:
```bash
./ar_remote_create.sh -n cp4i -r ar-demo
```
Outputs:
```
=== Initialising Asset repository with a remote ===
- Generating access token for user at https://cp-console.apps.fermi-dan-fyre-demos-operator.cp.fyre.ibm.com
=== Checking the route has been created ===
Waiting for asset repo route to be created, attempt number: 1...
✔ Asset repository as available at cpd-cp4i.apps.fermi-dan-fyre-demos-operator.cp.fyre.ibm.com/assets
=== Checking that Asset repository is live ===
✔ Asset repository contacted at cpd-cp4i.apps.fermi-dan-fyre-demos-operator.cp.fyre.ibm.com/assets
=== Checking if …
```
=> Only add the demos git remote to AR if not already added

products/bash/setup-demos.sh
```
[root@rhel84-node1 cp4i-deployment-samples]# ./products/bash/setup-demos.sh -i json1.json -o test.json
-------------------------------------------------------------------------------------------------------------------
ℹ Script directory: './products/bash'
ℹ Input file: 'json1.json'
ℹ Output file : 'test.json'
-------------------------------------------------------------------------------------------------------------------
ℹ [INFO] Checking if 'jq' is already installed...
jq-1.4
-------------------------------------------------------------------------------------------------------------------
ℹ [INFO] Checking if 'oc' is already installed...
Client Version: 4.7.19
Server Version: 4.6.56
Kubernetes Version: v1.19.16+6175753
[DEBUG] Got the following JSON for json1.json:
{ …
```
=> updated the jq

DrivewayDentDeletion/Operators/prereqs.sh, EventEnabledInsurance/build/build.sh, products/bash/1-click-install.sh, products/bash/1-click-pre-validation.sh, products/bash/change-cs-credentials.sh, products/bash/configure-apic-v10.sh, products/bash/configure-ocp-pipeline.sh, products/bash/create-ace-config.sh, products/bash/deploy-og-sub.sh, products/bash/release-navigator.sh, products/bash/release-psql.sh, products/bash/release-tracing.sh, products/bash/setup-demos.sh
Changes as per commit comments.
=> 1 click stability

products/bash/1-click-install.sh, products/bash/deploy-og-sub.sh, products/bash/release-tracing.sh
=> Faster storage, slow but safe operator install, fail if OD fails [DO NOT MERGE]

products/bash/deploy-og-sub.sh, products/bash/fix-usermgmt.sh, products/bash/release-navigator.sh
See issue: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54173
=> Workaround for Zen issue with usermgmt startup/upgrade

products/bash/create-catalog-sources.sh, products/bash/deploy-og-sub.sh, products/bash/find-catalog-sources/README.md
Signed-off-by: Lauren Stockley <lauren.stockley@ibm.com>
update catalog source names
=> change names of operators to match the upgrade doc

CommonPipelineResources/setup-pipeline.yaml, DrivewayDentDeletion/Operators/deploy-ia.sh, EventEnabledInsurance/build/deploy-ia.sh, products/bash/configure-apic-v10.sh, products/bash/create-catalog-sources.sh, products/bash/deploy-og-sub.sh, products/bash/find-catalog-sources/find-catalog-images.sh, products/bash/license-helper.sh, products/bash/release-ar.sh, products/bash/release-mq.sh, products/bash/release-navigator.sh, products/bash/utils.sh
change licenses and update operator images
=> 2023.4 changes

products/bash/1-click-install.sh, products/bash/1-click-pre-validation.sh
Removal of demo prep from the 1-click install script and removal of unnecessary validation
=> remove demos options

products/bash/1-click-install.sh, products/bash/release-assetrepo.sh
- After PN is created, AA is created
- Successful build: https://hyc-cip-jenkins.swg-devops.com/job/Automation/job/global_catalog_automation/369/console
Asset repo ready:
Part of: https://github.ibm.com/cp4i/singularity-planning/issues/765
=> adding asset repo release to one-click

products/bash/create-catalog-sources.sh, products/bash/deploy-og-sub.sh, products/bash/find-catalog-sources/find-catalog-images.sh, products/bash/release-assetrepo.sh, products/bash/release-navigator.sh
For: https://github.ibm.com/cp4i/singularity-planning/issues/767
Testing: https://hyc-cip-jenkins.swg-devops.com/job/Automation/job/global_catalog_automation/386
All new operators work:
New instances work:
=> feat: supporting the 16.1.0 release
